nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/sundiontheway

projects_url: http://github.com/sundiontheway

customize:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /image/sundi.jpg
        favicon: favicon.ico # path to favicon
    social_links:
        github: http://github.com/sundiontheway
        #twitter: /
        #facebook: /
        #linkedin: /
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: v2steve# Disqus Comments Shortname
    google_analytics: UA-64688885-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
